/**
 * Single import surface for SmoothHiring UI in the resources app.
 * Prefer these exports over duplicating styles in apps/resources.
 */
export {
  PrimaryThemeColor,
  PrimaryWordpressThemeColor,
  ResourceCTAColorBase,
  ShGreen,
  greenGradient,
  ShContainer,
  ShAppBar,
  ShPaper,
  ShButton,
  ShGreenBtn,
  ShBlueBtn,
  ShMuiLink,
  ShTextFieldV2,
  ShChip,
  ShLoader,
  ShLoadingDots,
  ShReactQuill,
  GradientBorder,
  ThemeColorDivider,
  ResourceHeroTitle,
  ResourceHeroBody,
  ResourceHeroCtaRow,
  ResourceActionRow,
  ResourceSectionHeading,
  ResourceSectionHeadingSecondary,
  ResourceSectionSubtitle,
  ResourceSectionStack,
  ResourceGridSection,
  ResourceCardDescription,
  ResourceCardWrapper,
  ResourceCTAStack,
  ResourceCTAStack as ResourceCtaStack,
  ResourceAiToolFormBody,
  ResourceAiToolFormRow,
  ResourceAiToolGeneratingStack,
  ResourceAiToolLoadingDotsHost,
  ResourceAiToolResultBody,
  ResourceActionRowEnd,
  ResourceActionRowInset,
  ResourceStackPrimaryAction,
  ResourceTemplateCardButton,
  ResourceFormControl,
  ShLogo,
  useIsSmScreen,
} from '@smoothhiring/smooth-ui';
